import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Theme from '@/component/theme'
import MiniDrawer from '@/component/sidebar'
const inter = Inter({ subsets: ['latin'] })
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
      </head>

      <body className={inter.className}>
      <Theme>
        <MiniDrawer>
            {children}
        </MiniDrawer>
      </Theme>
      </body>
    </html>
  )
}
